######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 12 15:11:28 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += analogclock.h mainwindow.h
SOURCES += analogclock.cpp main.cpp mainwindow.cpp
